### ISSUE TITLE
Batman web interface does not draw the graph

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#159] opened 2017-06-14 19:50 UTC
expected behaviour: graph of nodes at 
http://thisnode.info/cgi-bin/luci/batman/graph

actual behaviour: nothing is shown
![screenshot from 2017-06-14 22-50-19](https://user-images.githubusercontent.com/1136597/27151638-dd390740-5153-11e7-9442-e19763da3986.png)

code involved:
https://github.com/libremesh/lime-packages/blob/develop/packages/luci-app-batman-adv/files/usr/lib/lua/luci/controller/batman.lua

**Comment by FreifunkUFO** [comment] 2017-07-03 22:41
i tried that with former (karl helga openwrt cc) libremesh version firmware, there also was no graph.

**Comment by ilario** [comment] 2017-08-04 21:57
If I get this right, it's a duplicate of #110 and #1.
All of these issues depends on the fact that luci-app-batman-adv uses `batctl vd` for obtaining data, but this feature was moved to `batadv-vis` command which is part of the `alfred` package which is installed in all LibreMesh flavors (gets selected by dnsmasq-distributed-hosts and dnsmasq-lease-share packages).
So solving this could be as easy as replacing "batctl vd" for "batadv-vis" [here](/libremesh/lime-packages/blob/develop/packages/luci-app-batman-adv/files/usr/lib/lua/luci/controller/batman.lua#L75) (to be verified).

**Comment by p4u** [comment] 2017-08-13 11:10
PR on this issue would be very welcome :)

**Comment by ilario** [comment] 2017-09-21 10:28
Closed by #225

**Closed by ilario** 2017-09-21 10:28 UTC
Labels: duplicate, quickfix
