### ISSUE TITLE
command last_internet must filter better nodes of the network

### ISSUE THREAD

**Issue by spiccinini** [libremesh/lime-packages#683] opened 2020-01-31 14:00 UTC
Currently for babel it has a simple grep that verifies that ip starts with 10. We should use something better maybe https://stackoverflow.com/questions/30461623/bash-check-if-ip-in-subnet-range-file or https://unix.stackexchange.com/questions/258869/how-do-i-check-if-an-ip-address-or-a-network-is-contained-in-other-network-in-ba or use ip and network librery in lua.

**Comment by ilario** [comment] 2020-10-15 19:49
I just realized that this is a duplicate of #652

**Closed by ilario** 2020-10-15 19:49 UTC
Labels: bug
