### ISSUE TITLE
Set a better default distance parameter on the WiFi conifguration

### ISSUE THREAD

**Issue by p4u** [libremesh/lime-packages#201] opened 2017-08-03 15:43 UTC
Currently distance is set to 10000 (10Km). Reducing it to 1000 (1Km) would increase the network performance for most of the libremesh deployments. For those which are using long distance links, the distance should be set manually to ensure the best performance.

In addition to reduce the default distance, there should be a way to easy configure this parameter from the libremesh webui.

**Comment by ilario** [comment] 2017-08-03 16:06
What about a different distance setting for 2.4 GHz (usually clients) and for 5 GHz (usually mesh nodes)?
For example 200 m for 2.4 GHz and 5 km for 5 GHz. 

This is how it would be set in `/etc/config/lime-defaults`:
```
config lime wifi
	option distance_2ghz '200'
	option distance_5ghz '5000'
```

**Comment by p4u** [comment] 2017-08-03 16:17
I don't think this is possible on the WiFI configuration of LEDE. Actually, if I don't remember wrong, this parameter affects mainly to the 5GHz band.

**Comment by ilario** [comment] 2017-08-04 15:05
It should be possible, it has been implemented in LibreMesh [here](/libremesh/lime-packages/blob/develop/packages/lime-system/files/usr/lib/lua/lime/wireless.lua#L106), and in LEDE the configuration of different radios (2.4 GHz and 5 GHz) is separated, so it's the distance setting in LEDE for the two radios.
Even if nowadays maybe drivers for 2.4 GHz are not affected by this parameter, this could change.

**Comment by ilario** [comment] 2017-08-04 18:51
Closing as #202 has been merged.

**Comment by p4u** [comment] 2017-08-05 18:51
You are right, it can be set independently for the radios. It might be implemented as you proposed.

**Comment by nicoechaniz** [comment] 2017-08-06 23:42
When you are using dual band devices such as tl-wdr3500 the distance on each radio is the same. This is the most common scenario in the networks in our region. So a different value for 5Ghz and 2.4Ghz would not be our default.

**Comment by ilario** [comment] 2017-08-20 16:26
@nicoechaniz so in your scenario both 2.4 and 5 GHz are used for node to node connections? Isn't 2.4 GHz radio involved more heavily in node to client connections?

**Comment by digitigrafo** [comment] 2023-05-19 10:01
On 18/05/23 19:00, Ilario Gelmetti wrote:
>
> Let's reopen this discussion.
> @digitigrafo <https://github.com/digitigrafo> reported that plenty of 
> communities had problem with 1000 m as maximum default distance.
> I propose to set it to 5 km.
>
I reported it in 2019.. when I was in brasil and I find 2 communities 
that abandoned to use Lime because can't update from lime17 to lime19..

and was the same problem that we had.. lime 17 was working on long 
distance, so the feedback when you upgraded to 19 was:"libremesh is not 
more working" and there was not changelog to know what happen in the 
last release, and also the design of the project has an hole in that 
point (no config needed), but after speaking with the developers was 
easy to fix also in GUI using LUCI.. and our community survived.. but 
sadness.. for the others was too late. not possible without human 
communications and a bit of mutual aid..

I reported again in 2022 because last year also I meet 2 german 
communities that told me they tried to use Lime on ubnt m5 antennas 
already on the roof, passing from AirOS to Lime, but doesn't worked 
because the antennas lost connections with the others.. so yes the same 
problem of the distance. So out of that ecatombe of users in 2018-19... 
I think that still is a problem. because in the design the issue is 
still there. An in other side also the problem of communications between 
developers and communities is still there, when we change something that 
need to be re-configured by users is not clear that happen and where we 
announced. Github comments and matrix are not stable point of 
documentation. same when we introduced network profiles.. a lot of 
communities was not informed..

igni

**Comment by ilario** [comment] 2023-05-23 09:59
Please notice that this discussion forked on the mailing list, read the recent comments here: https://lists.autistici.org/thread/20230519.102407.1e38994a.en.html

**Comment by ilario** [comment] 2023-08-16 22:05
With @a-gave we made some measurements for understanding a bit better what happens when the distance parameter is much larger than the actual distance.
Clearly, the influence of this parameter will be strongly dependent on the quality of the link.
Anyway, on this thread we are sharing the results: 
https://lists.autistici.org/message/20230815.142621.071b5fc0.en.html

And on this repository you can find the code for repeating the measurement on your links (of for optimizing other parameters):
https://github.com/ilario/wifi-distance-setting-exploration

**Closed** 2023-09-15 06:45 UTC
Labels: enhancement
