### ISSUE TITLE
anygw: replace dnsmasq-dhcpv6 with odhcpd-ipv6only

### ISSUE THREAD

**Issue by aparcar** [libremesh/lime-packages#375] opened 2018-06-04 09:21 UTC
The latter is already standard for OpenWrt and comes preinstalled. It still creates entries in `/tmp/hosts` so DNS (sharing) shoudl continue to work.

**Comment by aparcar** [comment] 2018-06-13 03:50
related https://github.com/openwrt/odhcpd/issues/113

**Comment by nicopace** [comment] 2018-06-20 10:39
It is definitely one of the pain in the ass to be using dnsmasq as it breaks all the time.
I don't know how odhcpd behaves, we should test it out for robustness? or should we trust blindly? :)

**Comment by aparcar** [comment] 2018-06-20 10:45
odhcpd-ipv6only is used in LEDE stable and the upcoming 18.06 release, so it should be fairly stable. If I remember correct @dangowrt suggested this before, so I'm just following up on that.

odhcpd as a full dnsmasq dhcp replacement brings the current limitation that odhcpd does not (yet https://github.com/openwrt/odhcpd/issues/113) allow any lease input, meaning lease sharing wouldn't work. However, thats's may be tackeld by https://github.com/libremesh/lime-packages/issues/369

**Comment by aparcar** [comment] 2018-12-09 15:53
@dangowrt can you have a look at this and the ubus request posted a long time ago? https://github.com/openwrt/odhcpd/issues/113

**Comment by ilario** [comment] 2019-10-04 11:06
Seems that we gave up on this, as after years we still use dnsmasq.
Good thing is that dnsmasq seems more stable now.
I'm closing, please re-open if I'm wrong and this is still an open issue.

**Closed by ilario** 2019-10-04 11:06 UTC
Labels: enhancement

**Comment by ilario** [comment] 2019-10-04 17:26
Just realized that this was a duplicate of #294 and was being addressed by @aparcar in #379
