### ISSUE TITLE
GroundRouting: connecting internet with static IP

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#367] opened 2018-05-26 22:30 UTC
USECASE: ISPs that give static ips instead of dhcp in the network.

Expected behaviour: the app to allow the user to set the ip.

**Comment by G10h4ck** [comment] 2018-05-27 00:42
I believe groundrouting is not related to this usecase

**Comment by nicopace** [comment] 2018-05-30 05:57
Many of the conversations we have been having about how to reimplement groundrouting using media detection (mainly with @nicoechaniz ) include detecting what happens on the other side of the wire for every wire that is connected.
that is, if there is a dhcp server, if there is another libremesh device, or if there is none, and how to proceed with each.

**Comment by ilario** [comment] 2018-10-01 18:46
So it would be something like an **automatic** configuration for ground routing?

**Comment by nicopace** [comment] 2018-10-07 16:40
that is what was talked... but no progress on this yet... any volunteer @ilario  ;)

**Comment by ilario** [comment] 2018-12-08 20:40
@nicopace reading again the original description of the issue, sounds more like #429, right?
Autoconfiguration of groundrouting sounds like something too epic to do (we usually refer with "groundrouting" to a very specific thing).

**Comment by ilario** [comment] 2019-10-04 11:20
This issue is not clearly defined, I'm closing. Please feel free to re-open explaining it better. If it was actually a duplicate of #429, please reopen that issue instead of this one.

**Closed by ilario** 2019-10-04 11:20 UTC
Labels: enhancement, epic, needs more info
