### ISSUE TITLE
Configuration for reserving IP ranges for static assignations

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#106] opened 2017-03-31 01:08 UTC
Involves /etc/config/lime configs and LuCI interface implementation.

**Comment by ilario** [comment] 2017-04-23 15:35
Specifying IP autoconfiguration range for LiMe nodes (already implemented) and DHCP range (still to implement, see #33) should be enough for leaving a free range for static IPs.

**Comment by nicopace** [comment] 2017-04-23 19:49
This was a feature requested by @nicoechaniz . what do you think?

**Comment by ilario** [comment] 2017-05-25 18:50
One month without comments, closing as duplicate of #33.

**Closed by ilario** 2017-05-25 18:50 UTC
Labels: user story
