### ISSUE TITLE
Make Name Resolution work

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#132] opened 2017-05-21 13:40 UTC
note in spanish:
@altergui: resolucion de nombres (o alguna forma de conectarse con nodos) para los humanos q estan dentro de la red

**Comment by ilario** [comment] 2017-05-25 18:22
How should this work?
I thought we already had this (but I never used it).

**Comment by ilario** [comment] 2017-05-25 18:45
Is this related to #118?

**Comment by nicopace** [comment] 2017-05-29 15:25
no.
this is related to hostname and domain name resolution for both your cloud and other clouds.
like, if your node's hostname is 'nico' and network domain is 'quintana.libre.social', then everyone should be able to access it as nico.quintana.libre.social

**Comment by FreifunkUFO** [comment] 2017-07-03 23:26
its not a bug of libremesh firmware, but a possibile enhancement of your network setup.

so (seen from the internet), you network domain has to be 

* able to resolve your personal name (nico.quintana.libre.social) to an ipv4 OR/AND ipv6
* libremesh gateway node has to route that traffic
* libremesh gateway node has to firewall that traffic (do an accept)

do you have only one ipv4-ip on the gateway? so that would be difficult. you will need an http.proxy on the gateway node to direct the http-traffic to your special node/client. and its only working for http

do you have an small ipv6-subnet on the gateway? so you may think ipv6 sucks, arent there some more ips or do we reorder/NAT them?

do you have an big ipv6-subnet on the gateway? so it sounds nice. you still have to take a look at your firewall rules, even when your DNS with this ipv6-adresses is working properly..

**Comment by ilario** [comment] 2018-12-08 22:54
related: #193 #303 #390

**Comment by ilario** [comment] 2019-10-04 21:58
From *inside* of the network it already works.
What @FreifunkUFO writes is related to the possibility to access the host from outside of the network (internet) and is the object of #133.
Closing this.

**Closed** 2019-10-04 22:09 UTC
Labels: enhancement
